version: '3.5'
services:
  backup:
    #restart: unless-stopped
    build:
      context: .
    #user: "1000"
    volumes:
      - /tmp/backup_github_test:/backup
    # env_file:
    #  - .env
    environment:
      - SCHEDULE=12h
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
